# Generated by Django 5.0.7 on 2024-08-15 07:55

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_bar', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('new', 'L1_7'), ('active', 'L2_30'), ('completed', 'L3_30')], default='new', max_length=10)),
                ('dao_project', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('flag', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, max_length=4, unique=True)),
                ('tags', models.ManyToManyField(limit_choices_to={'max_tags': 3}, to='projects.tag')),
            ],
        ),
    ]
