# Generated by Django 5.0.7 on 2024-08-15 09:16

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_description_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Флаг страны'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kyc_verified',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_bar',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('new', 'L1_7'), ('active', 'L2_30'), ('completed', 'L3_30')], default='new', max_length=10, verbose_name='Сдадия'),
        ),
    ]
