# Generated by Django 5.0.7 on 2024-08-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_description_alter_project_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unique_id',
        ),
    ]
